apiVersion: v1
kind: Service
metadata:
  name: system-grafana-service
  namespace: prometheus
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - name: system-grafana
      port: 3000
      targetPort: 3000
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: mq-grafana-service
  namespace: nats
spec:
  type: NodePort
  selector:
    name: grafana
  ports:
    - name: mq-grafana
      port: 3000
      targetPort: 3000
      nodePort: 30001
