apiVersion: v1
kind: Service
metadata:
  name: nats-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: my-nats
    app.kubernetes.io/name: nats
    
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
      name: nats
    - protocol: TCP
      port: 6222
      targetPort: 6222
      name: cluster
    - protocol: TCP
      port: 7422
      targetPort: 7422
      name: leafnodes
    - protocol: TCP
      port: 7522
      targetPort: 7522
      name: gateways
    - protocol: TCP
      port: 8222
      targetPort: 8222
      name: monitor-port
    - protocol: TCP
      port: 7777
      targetPort: 7777
      name: metric-port