apiVersion: v1
kind: Service
metadata:
  name: prometheus2
  labels:
    app: prometheus2
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus
  sessionAffinity: ClientIP