apiVersion: v1
kind: Service
metadata:
  name: system-grafana
  namespace: prometheus
spec:
  type: ClusterIP
  clusterIP: 10.247.240.109
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - name: monitoring
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: mq-grafana
  namespace: rabbitmq-system
spec:
  type: ClusterIP
  clusterIP: 10.247.240.110
  selector:
    name: grafana
  ports:
    - name: metrics
      protocol: TCP
      port: 3001
      targetPort: 3000
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: kianian9/nginx_rabbit_grafana:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: system-grafana
      port: 80
      targetPort: 80
      nodePort: 30000
    - name: mq-grafana
      port: 81
      targetPort: 81
      nodePort: 30001
