apiVersion: v1
kind: Service
metadata:
  name: rabbit-http-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - name: amqp-port
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: management-port
      port: 15672
      protocol: TCP
      targetPort: 15672
