apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  # Used for limiting one broker to exactly one node
  #affinity:
  #  podAntiAffinity:
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #    - labelSelector:
  #        matchExpressions:
  #        - key: strimzi.io/name
  #          operator: In
  #          values:
  #          - kafka-cluster-kafka
  #      topologyKey: "kubernetes.io/hostname"

  # Temporary solution: Setting the limits to a very high value for removing benchmark restrictions
  resources:
    requests:
      cpu: 150m
      memory: 1Gi
    limits:
      #cpu: 500m
      cpu: 200000m
      #memory: 2Gi
      memory: 100Gi
  # Change this according to horiziontal scaling
  replicas: 3
  persistence:
    storageClassName: rabbit-sc
    storage: 5Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_federation
