apiVersion: v1
kind: Service
metadata:
  name: system-grafana
  namespace: prometheus
spec:
  type: ClusterIP
  clusterIP: 10.231.240.109
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - name: monitoring
      protocol: TCP
      port: 3000
      targetPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: mq-grafana
  namespace: nats
spec:
  type: ClusterIP
  clusterIP: 10.231.240.110
  selector:
    name: grafana
  ports:
    - name: metrics
      protocol: TCP
      port: 3001
      targetPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: nats-prometheus
  namespace: nats
spec:
  type: ClusterIP
  clusterIP: 10.231.240.111
  selector:
    app: prometheus
  ports:
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: kianian9/nginx_nats_grafana:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: system-grafana
      port: 80
      targetPort: 80
      nodePort: 30000
    - name: mq-grafana
      port: 81
      targetPort: 81
      nodePort: 30001
    - name: nats-prometheus
      port: 82
      targetPort: 82
      nodePort: 30002
    - name: nats-monitoring
      port: 83
      targetPort: 83
      nodePort: 30003
