apiVersion: v1
kind: Service
metadata:
  name: nats-service
spec:
  type: ClusterIP
  clusterIP: 10.231.240.2
  selector:
    app: prometheus
  ports:
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: kianian9/nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: nats-1
      port: 80
      targetPort: 80
      nodePort: 30000
    - name: nats-2
      port: 81
      targetPort: 81
      nodePort: 30001
