apiVersion: v1
kind: Service
metadata:
  name: stan-service
  labels:
    app: stan
spec:
  type: LoadBalancer
  #type: NodePort
  selector:
    app: my-stan
  ports:
    - name: client-port
      port: 4222
      targetPort: 4222
      #nodePort: 31001
    - name: metrics-port
      port: 7777
      targetPort: 7777
      #nodePort: 31002
    - name: monitor-port
      port: 8222
      targetPort: 8222
      #nodePort: 31003